apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secret.yaml
  - ../../base 
  - ingress.yaml

namespace: backend

images:
  - name: sprysio/efarm-backend
    newName: sprysio/efarm-backend
    newTag: develop-39d3e98b8045b72f436830028043cd78d4b450a3