# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sprysio/efarm-backend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: develop-0034a057e963c2f70c4b861bdddb239e837849e9

service:
  type: ClusterIP
  port: 8080

env:
  - name: MYSQL_DATABASE
    valueFrom: 
      secretKeyRef:
        name: back-secret
        key: MYSQL_DATABASE
  - name: MYSQL_DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: back-secret
        key: MYSQL_DATABASE_URL
  - name: MYSQL_USER
    valueFrom:
      secretKeyRef:
        name: back-secret
        key: MYSQL_USER
  - name: MYSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: back-secret
        key: MYSQL_PASSWORD
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: back-secret
        key: JWT_SECRET

resources:
  limits:
    cpu: 500m
    memory: 750Mi

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 60
readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 60


