apiVersion: apps/v1
kind: Deployment
metadata:
  name: efarm-backend
  namespace: backend
  labels:
    app: efarm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efarm-backend
  template:
    metadata:
      labels:
        app: efarm-backend
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: efarm-backend
          image: sprysio/efarm-backend
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: MYSQL_DATABASE_URL
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: MYSQL_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: back-secret
                  key: JWT_SECRET
          resources:
            limits:
              cpu: 500m
              memory: 750Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60