apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secret.yaml
  - ../../base 

namespace: backend

images:
  - name: sprysio/efarm-backend
    newName: sprysio/efarm-backend
    newTag: develop-b7af5e8d51b7fd724504807a6c60e47b7047242b