apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secret.yaml
  - ../../base 
  - ingress.yaml

namespace: backend

images:
  - name: sprysio/efarm-backend
    newName: sprysio/efarm-backend
    newTag: develop-f204f975b16b925d091ebdf8034b6f86a853246f