name: Cache on main branch

on:
  push:
    branches:
      - 'main'
      
jobs:
  cache-main:
    name: Cache
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
            ${{ runner.os }}-maven-

    - name: Install Profile Spotbugs and owasp
      run: mvn clean install -Pspotbugs-and-owasp -DNVD_API_KEY=${{ secrets.NVD_API_KEY }} -B 
    
    - name: Install Profile unit-test
      run: mvn clean install -Punit-test -DskipTests -B         
      
    - name: Install Profile integrationtest
      run: mvn clean install -Punit-test -DskipTests -B    

    - name: Install Profile default
      run: mvn clean install -B  
