name: Cache Dependencies And CodeQL

on:
  push:
    branches:
      - 'develop'
      
jobs:
  cache-codeql:
    name: Make Cache and Scan with CodeQL
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
            ${{ runner.os }}-maven-
        
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'java'

    - name: Install Dependencies, Build, Trigger Spotbugs and Dependency Check
      run: mvn clean install -DskipTests -DNVD_API_KEY=${{ secrets.NVD_API_KEY }} -B

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3  