name: Seret Scanning, Spotbugs and OWASP 

on:
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'

jobs:
  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Secret Scanning
        uses: secret-scanner/action@0.0.2

  lint-scan:
    name: Lint and Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Cache Maven dependencies
      uses: actions/cache/restore@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
            ${{ runner.os }}-maven-
                 
    - name: Install Dependencies, Build, Trigger Spotbugs and Dependency Check
      run: mvn clean verify -Pspotbugs-and-owasp -DNVD_API_KEY=${{ secrets.NVD_API_KEY }} -B

    - name: Upload SpotBugs and Dependency Check Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: reports
        path: |
          target/spotbugs.html
          target/dependency-check-report.html