name: Cache Maven Dependencies with Profiles

on:
  push:
    branches:
      - 'feature/*'

jobs:
  cache-dependencies:
    name: Cache Maven Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [spotbugs-and-owasp,unit-test, integrationtest,default]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Cache Maven dependencies and plugins
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.m2/plugin-registry
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-${{ matrix.profile }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ matrix.profile }}-
          ${{ runner.os }}-maven-

    - name: Install Dependencies and Build
      run: mvn clean install -P${{ matrix.profile }} -B
